# toml-docs-start main
[main]
    separator = "-"
    description = "Hi! I'm Martin Bustos, an indie game developer and asset store publisher"
    enableDarkMode = true
    modes = ["dark"]
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    disableComments = false
    [main.externalLinks]
        cue = true
        tab = true
    [main.build]
        transpiler = "libsass"
# toml-docs-end main

# toml-docs-start images
[images]
    [images.cloudinary]
        host = "cloudinary"
    [images.imagekit]
        host = "imagekit"
    [images.imgix]
        host = "imgix"
# toml-docs-end images

# toml-docs-start debugging
[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false
# toml-docs-end debugging

# toml-docs-start docs
[docs]
    github = "https://github.com/gethinode/hinode"
    release = "https://github.com/gethinode/hinode/releases/tag/"
    checkVersion = false
# toml-docs-end docs

# toml-docs-start home
[home]
    sections = ["store", "projects", "blog"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 5
        align = "start"
# toml-docs-end home

# toml-docs-start navigation
[navigation]
    anchor = true
    logo = "/img/logo_icon.png"
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
# toml-docs-end navigation

# toml-docs-start messages
[messages]
    placement = "bottom-right"
# toml-docs-end messages

# toml-docs-start sharing
[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Bluesky"
    url = "https://bsky.app/profile/{url}.bsky.social"
    icon = "fab bluesky"
    weight = 22

[[sharing.providers]]
    name = "Instagram"
    url = "https://www.instagram.com/{url}/"
    icon = "fab instagram"
    weight = 25

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true
# toml-docs-end sharing

# toml-docs-start sections
[sections]
    [sections.store]
        title = "Store"
        sort = "date"
        reverse = false
        cols = 3
        color = ""
        padding = "0"
        header = "none"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 6
        separator = true
    [sections.projects]
        title = "Projects"
        layout = "card"
        sort = "date"
        reverse = true
        nested = true
        cols = 3
        background = "body-tertiary"
        color = "body"
        padding = "3"
        header = "none"
        footer = "none"
        orientation = "horizontal"
        style = "border-1 card-emphasize"
        homepage = 6
        separator = false
    [sections.projects.kairos]
        title = "Kairos"
        sort = "date"
        reverse = true
        cols = 3
        color = ""
        padding = "0"
        header = "none"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 6
        separator = true
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = false
        cols = 3
        color = ""
        padding = "0"
        header = "none"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 6
        separator = true
# toml-docs-end sections

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#f4a410"
    #primary = "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
# toml-docs-end theme-colors
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
# toml-docs-start font
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    themeFontPreload = "/fonts/inter-v12-latin-regular.woff2"
    fontSizeBase = "1rem" # assumes the browser default, typically '16px'
# toml-docs-end font
# toml-docs-start build
    purge = false
# toml-docs-end build

[schema]
    type = "Organization"
    name = "Fronkon Games"
    locale = "es-ES"
    twitter = "https://x.com/fronkongames"
    instagram = "https://www.instagram.com/fronkongames/"
    linkedIn = "https://www.linkedin.com/in/martinbr"
    github = "https://github.com/FronkonGames"
    section = "blog"
    [author]
        name = "Martin Bustos"
        twitter = "https://x.com/fronkongames"
        linkedIn = "https://www.linkedin.com/in/martinbr"
        instagram = "https://www.instagram.com/fronkongames/"
        github = "https://github.com/FronkonGames"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "es_ES"

[links]
    hinode = "https://gethinode.com"
    supportEmail = "mailto:fronkongames@gmail.com"
    fronkonGamesWeb = "https://fronkongames.github.io/"

[giscus]
    # The GitHub repository, required.
    repo = "FronkonGames/fronkongames.github.io"
    # The GitHub repository ID, optional. We'll fetch the repo ID by GitHub REST API if omitted.
    # It's recommend to specify it to save the build time.
    repo_id = "R_kgDOIyuXfQ"

    # Discussion category, required.
    category = "Comments"
    # Discussion category ID, required, since GitHub doesn't provide REST API for discussions.
    category_id = "DIC_kwDOIyuXfc4Cf3OB"

    # The mapping between the embedding page and the embedded discussion. Available options:
    #   pathname: giscus will search for a discussion whose title contains the page's pathname URL component.
    #   URL:      giscus will search for a discussion whose title contains the page's URL.
    #   title:    giscus will search for a discussion whose title contains the page's <title> HTML tag.
    #   og:title: giscus will search for a discussion whose title contains the page's <meta property="og:title"> HTML tag.
    mapping = "og:title"

    # Use strict title matching, avoid mismatches due to GitHub's fuzzy searching method when there are multiple discussions with similar titles.
    strict_matching = true

    # Theme. Available options:
    #   light:                  GitHub Light.
    #   light_high_contrast:    GitHub Light High Contrast.
    #   light_protanopia:       GitHub Light Protanopia & Deuteranopia.
    #   light_tritanopia:       GitHub Light Tritanopia.
    #   dark:                   GitHub Dark.
    #   dark_high_contrast:     GitHub Dark High Contrast.
    #   dark_protanopia:        GitHub Dark Protanopia & Deuteranopia.
    #   dark_tritanopia:        GitHub Dark Tritanopia.
    #   dark_dimmed:            GitHub Dark Dimmed.
    #   transparent_dark:       Transparent Dark.
    #   preferred_color_scheme: Preferred color scheme.
    #   an URL of external CSS. It may be unsafe, make sure you trust the author and provider of the CSS file.
    theme = "dark"

    # The input position. Available options:
    #   top:    above the comments.
    #   bottom: below the comments.
    input_position = "top"

    # Enable reactions for the main post.
    reactions = true

    # Load the comments lazily.
    lazy_loading = true

    # The languages mapping from site language to Giscus language.
    # Since the Giscus doesn't support all languages and the language is case sensitive.
    # Available languages:
    #  - ar
    #  - de
    #  - gsw
    #  - es
    #  - en
    #  - fr
    #  - id
    #  - it
    #  - ja
    #  - ko
    #  - pl
    #  - pt
    #  - ro
    #  - ru
    #  - tr
    #  - vi
    #  - zh-CN
    #  - zh-TW
    [languages_mapping]
      en-us = "en"