######################## default configuration ####################
baseURL = "https://fronkongames.github.io/"
languageCode = "en-us"
title = "Fronkon Games"
theme = ["restaurant-hugo", "hugo-shortcode-gallery"]
summaryLength = "10"
paginate = 4
enableRobotsTXT = true
enableEmoji = true
relativeurls = true
uglyurls = true
publishDir = "/docs"
timeout = 90

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Assets"
URL = "store"
weight = 2

[[menu.main]]
name = "Games"
URL = "games"
weight = 3

[[menu.main]]
name = "Gamedev"
URL = "gamedev"
weight = 4

[[menu.main]]
name = "Fun"
URL = "blog"
weight = 5

#[[menu.main]]
#name = "About Me"
#URL = "about-me"
#weight = 3

#[[menu.main]]
#name = "Price"
#URL = "price"
#weight = 4

#[[menu.main]]
#name = "News"
#URL = "subscribe"
#weight = 5

[[menu.main]]
name = "Contact"
URL = "footer"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
featured = "images/featured.jpg"

# meta data
author = "Martin Bustos"
description = "Indie game developer and asset publisher"
keywords = "gamedev, unity, asset, store, unity3d, videogames, programmer"

# Google Analitycs 4 ID
googleAnalyticsID = "G-90Y4J5LX9J"

# mainSections
main_sections = ["post"]

# copyright
copyright = "Copyright &copy; 2024 Fronkon Games"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Store ############################
[params.store]
enable = true

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "contact <span>me</span> "
blogTitle = "LATEST <span>BLOG POSTS</span>"
#galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "it's <span>alive!</span>"

############################ footer contact item
#[[params.footer.contactItem]]
#title = "Telephone"
#icon = "fa fa-phone"
#content = "016742 323313"

#[[params.footer.contactItem]]
#title = "Address"
#icon = "fa fa-map-marker"
#content = "2046 Blue Spruce Lane Laurel Canada"

[[params.footer.contactItem]]
title = "E mail"
icon = "fa fa-envelope"
content = "fronkongames@gmail.com"

######################### footer gallery
#[[params.footer.gallery]]
#image = "images/slider/slider-img-1.jpg"

#[[params.footer.gallery]]
#image = "images/slider/slider-img-2.jpg"

#[[params.footer.gallery]]
#image = "images/slider/slider-img-3.jpg"

#[[params.footer.gallery]]
#image = "images/slider/slider-img-4.jpg"

#[[params.footer.gallery]]
#image = "images/slider/slider-img-1.jpg"

#[[params.footer.gallery]]
#image = "images/slider/slider-img-2.jpg"

######################## Social Icon 
#[[params.footer.socialLink]]
#icon = "facebook"
#link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://twitter.com/fronkongames"

[[params.footer.socialLink]]
icon = "github"
link = "https://github.com/FronkonGames"

[[params.footer.socialLink]]
icon = "linkedin"
link = "https://www.linkedin.com/in/martinbr"

#[[params.footer.socialLink]]
#icon = "dribbble"
#link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "youtube"
link = "https://www.youtube.com/@fronkongames"

[imaging.exif]
includeFields = ".*"

[module]
  [module.hugoVersion]
    extended = true