[[main]]
  name = "STORE"
  pageRef = "/store/"
  weight = 10

[[main]]
  name = "PROJECTS"
  pageRef = "/projects/"
  weight = 20

[[main]]
  name = "BLOG"
  pageRef = "/blog/"
  weight = 30

# [[main]]
#   name = "ABOUT"
#   pageRef = "/about/"
#   weight = 40

[[social]]
  name = "eMail"
  pre = "fa envelope"
  url = "mailto:fronkongames@gmail.com"
  weight = 1

[[social]]
  name = "Unity"
  pre = "fab unity"
  url = "https://assetstore.unity.com/publishers/62716"
  weight = 5

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/FronkonGames"
  weight = 10

[[social]]
  name = "Bluesky"
  pre = "fab bluesky"
  url = "https://bsky.app/profile/fronkongames.bsky.social"
  weight = 20

[[social]]
  name = "Twitter"
  pre = "fab x-twitter"
  url = "https://x.com/fronkongames"
  weight = 30

[[social]]
  name = "Youtube"
  pre = "fab youtube"
  url = "https://www.youtube.com/@fronkongames"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/in/martinbr"
  weight = 50
